#!/bin/bash

file_name=`echo $1 | sed -e s'/\./ /'g | awk '{print $1}'`

if [ "$1" == '' ] ; then
   echo "Usage: split_geom <filename>"
   exit
else
    mbconvert $1 -1 $file_name"_curves.vtk"
    mbconvert $1 -2 $file_name"_facets.vtk"
fi

exit