version: 2.1
jobs:
  house_keeping:
    parameters:
      img:
        type: string
    docker:
      - image: svalinn/dagmc-ci-ubuntu-18.04-housekeeping:latest
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS
    working_directory: /root/build_dir/DAGMC
    steps:
      - checkout
      - run:
          name: Setup environment
          command: |
            echo "export REPO_SLUG=${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PR_REPONAME}" >> $BASH_ENV
            echo "export PULL_REQUEST=${CIRCLE_PR_NUMBER}" >> $BASH_ENV
      - run:
          name: Housekeeping
          command: CI/circleci/housekeeping.sh

  build_and_test:
    parameters:
      img:
        type: string
      compiler:
        type: string
      hdf5:
        type: string
      moab:
        type: string
      double_down:
        type: string
        default: "OFF"
    docker:
      - image: svalinn/dagmc-ci-ubuntu-<< parameters.img >>-<< parameters.compiler >>-ext-hdf5_<< parameters.hdf5 >>-moab_<< parameters.moab >>:latest
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS
    working_directory: /root/build_dir/DAGMC
    steps:
      - checkout
      - run:
          name: Setup environment
          command: |
            echo "export COMPILER=<< parameters.compiler >>" >> $BASH_ENV
            echo "export MOAB_VERSION=<< parameters.moab >>" >> $BASH_ENV
            echo "export REPO_SLUG=${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PR_REPONAME}" >> $BASH_ENV
            echo "export PULL_REQUEST=${CIRCLE_PR_NUMBER}" >> $BASH_ENV
            echo "export DOUBLE_DOWN=<< parameters.double_down >>" >> $BASH_ENV
      - run:
          name: Building DAGMC
          command: CI/circleci/install.sh
      - run:
          name: Testing DAGMC
          command: CI/circleci/tests.sh

workflows:
  version: 2
  pull_request: # Run only for PullRequest
    jobs:

      - house_keeping:
          context: dockerhub
          matrix:
            parameters:
              img: ["18.04"]
          filters:
            branches:
              ignore: develop

      - build_and_test:
          context: dockerhub
          matrix:
            parameters:
              img: [ "16.04", "18.04"]
              compiler: ["clang", "gcc"]
              moab: ["Version5.1.0"]
          requires:
            - house_keeping
          filters:
            branches:
              ignore: develop

  merge:  # Run only on develop change -> when merging a PullRequest
    jobs:
      - build_and_test:
          context: dockerhub
          matrix:
            parameters:
              img: [ "16.04", "18.04"]
              compiler: ["clang", "gcc"]
              moab: ["Version5.1.0", "develop", "master"] # this should be a specific MOAB branch that exist on https://bitbucket.org/fathomteam/moab
          filters:
            branches:
              only: develop
      - build_and_test:
          context: dockerhub
          name: "Double Down"
          img: "18.04"
          compiler: "gcc"
          hdf5: "1.10.4"
          moab: "master"
          double_down: "ON"
          filters:
            branches:
              only: develop
