#! /bin/bash

#Exit it any error is returned
set -e

###NOTE: FILE EXPECTED TO BE RUN IN DIR WITH REFERENCED .h5m FILES!!!##### Single verticie move test
echo
echo CONE TESTS:
echo TEST 1: SINGLE VERT BUMP

python bump_vert.py --filename cones.h5m  &>-

../check_watertight cones_mod.h5m -f 1e-04

../make_watertight cones_mod.h5m &>- 

../check_watertight cones_mod_zip.h5m -f 1e-04

echo

echo CONE TESTS:
echo TEST 2: SERIES VERT BUMP

python bump_vert.py --filename cones.h5m  &>-

echo
echo BEFORE:
../check_watertight cones_mod.h5m -f 1e-04

../make_watertight cones_mod.h5m &>- 

echo
echo AFTER:
../check_watertight cones_mod_zip.h5m -f 1e-04

echo
exit 0
