#! /bin/bash

#Exit if any error is returned
set -e

###NOTE: FILE EXPECTED TO BE RUN IN DIR WITH REFERENCED .h5m FILES!!!####

# Single verticie move test
echo
echo CYLINDER TESTS:
echo TEST 1: SINGLE VERT BUMP
python bump_vert.py --filename cyl.h5m &>-

echo
echo BEFORE:

../check_watertight cyl_mod.h5m

../make_watertight cyl_mod.h5m &>- 

echo
echo AFTER:
../check_watertight cyl_mod_zip.h5m 

echo
echo TEST 2: SERIES VERT BUMP
python bump_verts.py --filename cyl.h5m &>-

echo
echo BEFORE:
../check_watertight cyl_mod.h5m

../make_watertight cyl_mod.h5m &>- 

echo
echo AFTER:
../check_watertight cyl_mod_zip.h5m 

echo
exit 0


