FROM ubuntu:16.04

# Use bash as the default shell
RUN ln -snf /bin/bash /bin/sh

# Update core packages
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get -y dist-upgrade

# Get some apt packages
RUN apt-get -y install autoconf
RUN apt-get -y install clang
RUN apt-get -y install cmake
RUN apt-get -y install g++
RUN apt-get -y install gcc
RUN apt-get -y install gfortran
RUN apt-get -y install git
RUN apt-get -y install libblas-dev
RUN apt-get -y install libhdf5-dev
RUN apt-get -y install liblapack-dev
RUN apt-get -y install libpython2.7-dev
RUN apt-get -y install libtool
RUN apt-get -y install python-numpy
RUN apt-get -y install python-pip
RUN apt-get -y install python-setuptools
RUN apt-get -y install wget

# Get 18.04 version of astyle
RUN astyle_deb=astyle_3.1-1ubuntu2_amd64.deb && \
    wget https://launchpad.net/ubuntu/+source/astyle/3.1-1ubuntu2/+build/14532685/+files/${astyle_deb} && \
    dpkg -i ${astyle_deb} && \
    rm -f ${astyle_deb}

# Get some pip packages
RUN pip install cython
RUN pip install sphinx

# Copy the environment variable script
RUN mkdir -p /root/etc/
COPY env.sh /root/etc/

# Build HDF5
COPY build_hdf5.sh /root/etc/
RUN bash /root/etc/build_hdf5.sh gcc   1.10.4
RUN bash /root/etc/build_hdf5.sh clang 1.10.4

# Build Geant4
COPY build_geant4.sh /root/etc/
RUN bash /root/etc/build_geant4.sh gcc
RUN bash /root/etc/build_geant4.sh clang

# Build MOAB 5.1.0
COPY build_moab.sh /root/etc/
RUN bash /root/etc/build_moab.sh gcc   system 5.1.0
RUN bash /root/etc/build_moab.sh clang system 5.1.0
RUN bash /root/etc/build_moab.sh gcc   1.10.4 5.1.0
RUN bash /root/etc/build_moab.sh clang 1.10.4 5.1.0
