FROM ubuntu:18.04

# Use bash as the default shell
RUN ln -snf /bin/bash /bin/sh

# Update core packages
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get -y dist-upgrade

# Get some apt packages
RUN apt-get -y install autoconf clang cmake g++ gcc gfortran git libblas-dev \
                       libhdf5-dev liblapack-dev libpython2.7-dev libtool \
                       python-numpy python-pip python-setuptools wget

# Get astyle
RUN apt-get -y install astyle

# Get some pip packages
RUN pip install cython sphinx

# Copy the environment variable script
RUN mkdir -p /root/etc/
COPY env.sh /root/etc/

# Build HDF5
COPY build_hdf5.sh /root/etc/
RUN bash /root/etc/build_hdf5.sh gcc   1.10.4
RUN bash /root/etc/build_hdf5.sh clang 1.10.4

# Build Geant4
COPY build_geant4.sh /root/etc/
RUN bash /root/etc/build_geant4.sh gcc
RUN bash /root/etc/build_geant4.sh clang

# Build MOAB 5.1.0
COPY build_moab.sh /root/etc/
RUN bash /root/etc/build_moab.sh gcc   system 5.1.0
RUN bash /root/etc/build_moab.sh clang system 5.1.0
RUN bash /root/etc/build_moab.sh gcc   1.10.4 5.1.0
RUN bash /root/etc/build_moab.sh clang 1.10.4 5.1.0
