#!/bin/bash

echo "running test spherical shells on FLUKA..."
cd fluka
$FLUPRO/flutil/rfluka -N0 -M5 spheres.inp
cp ../prod_data .
./prod_data

cd ..
echo "running test spherical shells on FluDAG..." 
cd fludag
$FLUPRO/flutil/rfluka -N0 -M5 -e /opt/DAGMC/FluDAG/bin/mainfludag -d spheres.h5m spheres.inp
cp ../prod_data .
./prod_data

cd ..
echo "Comparing results..."
./get_data
