
#define DAGMC_VERSION 3.0
#define DAGMC_VERSION_STRING "3.0"
#define DAGMC_INTERFACE_REVISION "$Rev$"

// THE ORDER OF LINES IN THIS FILE IS
// IMPORTANT TO CMAKE CONFIGURATION OF
// THE DAGMC VERSION NUMBER, CHANGE
// WITH CARE
