name: Test newest version of upstream dependencies on merge
description: Builds and tests the newest merged version of DAGMC against newer versions of upstream dependencies
inputs:
  token:
    description: token for logging in to the GHCR
    required: true
    default: ''
  geant4_version:
    description: Version of Geant4
    required: false
    default: off
  ubuntu_version:
    description: Underlying OS version
    required: false
    default: 22.04
  compiler:
    description: which compiler to use gcc or clang
    required: false
    default: gcc
  hdf5_version:
    description: Version of HDF5
    required: false
    default: hdf5_1_14_3
  moab_version:
    description: Version of MOAB
    required: false
    default: 5.5.1
  double_down_version:
    description: Version of Double Down
    required: false
    default: off

runs:
  using: "composite"
  steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ inputs.token }}

      - name: Installing Dependencies in Docker image
        uses: firehed/multistage-docker-build-action@v1
        with:
          repository: >
            ghcr.io/${{
              github.repository_owner
            }}/dagmc-ci-ubuntu-${{
              inputs.ubuntu_version
            }}-${{
              inputs.compiler
            }}-hdf5_${{
              inputs.hdf5_version
            }}-moab_${{
              inputs.moab_version
            }}-geant4_${{
              inputs.geant4_version
            }}-double_down_${{
              inputs.double_down_version
            }}
          stages: base, external_deps, dagmc
          server-stage: dagmc_test
          quiet: false
          parallel: true
          tag-latest-on-default: false
          dockerfile: CI/Dockerfile
          build-args: >
            UBUNTU_VERSION=${{ inputs.ubuntu_version }}, 
            COMPILER=${{ inputs.compiler }}, 
            HDF5_VERSION=${{ inputs.hdf5_version }}, 
            MOAB_VERSION=${{ inputs.moab_version }}, 
            GEANT4_VERSION=${{ inputs.geant4_version }}, 
            DOUBLE_DOWN_VERSION=${{ inputs.double_down_version }}
