ARG UBUNTU_VERSION=18.04
ARG COMPILER=gcc
ARG HDF5=1.10.4
ARG MOAB=5.1.0
FROM svalinn/test_dagmc-ci-ubuntu-${UBUNTU_VERSION}-${COMPILER}-g4-hdf5_${HDF5}-moab_${MOAB}

ARG EMBREE=OFF
RUN if [ "${EMBREE}" == ON ]; then \
        /root/etc/CI/docker/build_embree.sh; \
    fi;
