ARG UBUNTU_VERSION=18.04
FROM ubuntu:${UBUNTU_VERSION}

# Use bash as the default shell
SHELL ["/bin/bash", "-c"]

# Update core packages
ARG UBUNTU_VERSION=18.04
RUN apt-get -y update; \
    apt-get -y install autoconf clang cmake g++ gcc gfortran git libblas-dev \
                       libhdf5-dev liblapack-dev libpython2.7-dev libtool libeigen3-dev\
                       python-numpy python-pip python-setuptools wget; \
    if [ "${UBUNTU_VERSION}" = "18.04" ]; then \
        pip install sphinx; \
        apt-get -y install astyle; \
    fi; \
    pip install cython

# Copy scripts to docker image
RUN mkdir -p /root/etc/
COPY CI/ /root/etc/CI
ENV docker_env=/root/etc/CI/env.sh

ENV build_dir=/root/build_dir
ENV install_dir=/root/opt
ENV geant4_build_dir=${build_dir}/geant4
ENV geant4_install_dir=${install_dir}/geant4
ENV hdf5_build_dir=${build_dir}/hdf5
ENV hdf5_install_dir=${install_dir}/hdf5
ENV moab_build_dir=${build_dir}/moab
ENV moab_install_dir=${install_dir}/moab

