ARG UBUNTU_VERSION=18.04
FROM ubuntu:${UBUNTU_VERSION}

# Use bash as the default shell
SHELL ["/bin/bash", "-c"]

# Update core packages
RUN apt-get -y update; \
    apt-get -y install autoconf \
                       clang \
                       cmake \
                       g++ \
                       gcc \
                       gfortran \
                       git \
                       libblas-dev \
                       libhdf5-dev \
                       liblapack-dev \
                       libtool \
                       libeigen3-dev\
                       python-numpy \
                       python3.8-pip \
                       python3.8-setuptools \
                       python3.8-dev \
                       libpython3.8-dev \
                       wget; \
    pip install cython; \
    update-alternatives --install /usr/bin/python python /usr/bin/python3 10; \
    update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 10; \

# Copy scripts to docker image
RUN mkdir -p /root/etc/
COPY CI/ /root/etc/CI
ENV docker_env=/root/etc/CI/env.sh

ENV build_dir=/root/build_dir
ENV install_dir=/root/opt
