ARG UBUNTU_VERSION=18.04
FROM svalinn/test_dagmc-ci-ubuntu-${UBUNTU_VERSION}

ARG COMPILER=gcc
ONBUILD ENV COMPILER=${COMPILER}

# Set Geant4 env variable
run  echo 'export geant4_build_dir=${build_dir}/geant4' >> $BASH_ENV
run  echo 'export geant4_install_dir=${install_dir}/geant4' >> $BASH_ENV

# Build Geant4
RUN /root/etc/CI/docker/build_geant4.sh 

