ARG UBUNTU_VERSION=18.04
FROM svalinn/test_dagmc-ci-ubuntu-${UBUNTU_VERSION}

ARG COMPILER=gcc
ENV COMPILER=${COMPILER}
RUN echo "toto"
# Set Geant4 env variable
ENV geant4_build_dir=${build_dir}/geant4
ENV geant4_install_dir=${install_dir}/geant4

# Build Geant4
#RUN /root/etc/CI/docker/build_geant4.sh 

