#!/bin/bash

rm -rf *.h5m *.stl

dagmc_preproc -f 1.0e-2 cylinder.sat -o cylinder.h5m

cp cylinder.h5m cylinder_mod.h5m

chmod u+x bump_verts.py

./bump_verts.py cylinder_mod.h5m

check_watertight cylinder.h5m false 1.0e-2

check_watertight cylinder_mod.h5m false 1.0e-2

check_watertight cylinder_mod.h5m false 1.0e-3

mbconvert cylinder_mod.h5m cylinder_mod.stl
mbconvert cylinder.h5m cylinder.stl

