#!/usr/bin/python
"""
List of pre-defined single-element FLUKA materials
"""
Fluka_predefined_mat=["BERYLLIU","BARIUM","BISMUTH","BROMINE","RHENIUM","RUTHERFO","ROENTGEN","HYDROGEN","PHOSPHO","GERMANIU",
"GADOLINI","GALLIUM","HASSIUM","ZINC","HAFNIUM","MERCURY","HELIUM","PRASEODY","PLATINUM","239-PU","LEAD","CARBON", "POTASSIU","OXYGEN","SULFUR","TUNGSTEN","EUROPIUM","MAGNESIU","MOLYBDEN","MANGANES","URANIUM","IRON","NICKEL","NITROGEN",
"SODIUM","NIOBIUM","NEODYMIU","NEON","ZIRCONIU","BORON","COBALT","FLUORINE","CALCIUM","CERIUM","CADMIUM","VANADIUM","CESIUM",
"CHROMIUM","COPPER","STRONTIU","KRYPTON","SILICON","TIN","SAMARIUM","SCANDIUM","ANTIMONY","LANTHANU","CHLORINE","LITHIUM",
"TITANIUM","TERBIUM","99-TC", "TANTALUM","SILVER","IODINE","IRIDIUM","241-AM","ALUMINUM","ARSENIC","ARGON","GOLD","INDIUM",
"YTTRIUM","XENON","HYDROG-1","DEUTERIU","TRITIUM","HELIUM-3","HELIUM-4","LITHIU-6","LITHIU-7","BORON-10","BORON-11","90-SR",
"129-I","124-XE","126-XE","128-XE","130-XE","131-XE","132-XE","134-XE","135-XE","136-XE","135-CS","137-CS", "230-TH","232-TH",
"233-U","234-U","235-U","238-U"]


"""
def: Fluka_list is a list of predefined Fluka materials (only names)
"""
"""
Fluka_predefined_mat=['BLCKHOLE', 'VACUUM', 'HYDROGEN', 'HELIUM', 'BERYLLIU', 'CARBON', 'NITROGEN', 'OXYGEN', 'MAGNESIU', 'ALUMINUM', 'IRON', 'COPPER', 'SILVER', 'SILICON', 'GOLD', 'MERCURY', 'LEAD', 'TANTALUM', 'SODIUM', 'ARGON', 'CALCIUM', 'TIN', 'TUNGSTEN', 'TITANIUM', 'NICKEL']

"""
