find_path(MOAB_INCLUDE_DIR
  NAMES MBiMesh.hpp
  PATHS ${MOAB_ROOT} ENV MOAB_ROOT ENV LD_LIBRARY_PATH
  PATH_SUFFIXES include Include
  NO_DEFAULT_PATH
)

find_library(MOAB_LIBRARY
  NAMES MOAB
  PATHS ${MOAB_ROOT} ENV MOAB_ROOT ENV LD_LIBRARY_PATH
  PATH_SUFFIXES lib Lib
  NO_DEFAULT_PATH
)

set(MOAB_LIBRARIES ${MOAB_LIBRARY})
set(MOAB_INCLUDE_DIRS ${MOAB_INCLUDE_DIR})

if (MOAB_INCLUDE_DIR AND MOAB_LIBRARY)
  message(STATUS "MOAB_INCLUDE_DIRS: ${MOAB_INCLUDE_DIR}")
  message(STATUS "MOAB_LIBRARIES: ${MOAB_LIBRARY}")
else ()
  message(FATAL_ERROR "Could not find MOAB")
endif ()
