# This Macro sets up the download and build of MOAB using ExternalProject
# few tweak are done in src/dagmc/CMakeLists.txt and src/PyNE/CMakeists.txt 
# to make sure that MOAB is built before DAGMC.
MACRO (moab_pull_make MOAB_Version)
  MESSAGE(STATUS "MOAB will be downloaded and built")
  
  # Ensure STATIC LIBS Build
  IF(DAGMC_BUILD_STATIC_LIBS)
    MESSAGE(FATAL_ERROR "PULL_INSTALL_MOAB is ONLY compatible with shared libraries.")
  endIF()
    
  # Ensure we have the right variables to build MOAB
  moab_autobuild_check_deps()
   
    
  INCLUDE(ExternalProject)
  MESSAGE("HDF5_ROOT: ${HDF5_ROOT}")
  SET(MOAB_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}/moab")
  SET(MOAB_ROOT "${CMAKE_BINARY_DIR}/moab")
  SET(MOAB_INCLUDE_DIRS "${MOAB_INSTALL_PREFIX}/include")
  SET(MOAB_LIBRARY_DIRS "${MOAB_INSTALL_PREFIX}/lib")
  MESSAGE("MOAB_LIBRARY_DIRS: ${MOAB_LIBRARY_DIRS}")
  MESSAGE("CMAKE_SHARED_LIBRARY_SUFFIX: ${CMAKE_SHARED_LIBRARY_SUFFIX}")
  MESSAGE("MOAB_Version: ${MOAB_Version}")
  SET(MOAB_LIBRARIES_SHARED "")
  ExternalProject_Add(MOAB_ep
    PREFIX ${MOAB_ROOT}   
    GIT_REPOSITORY https://bitbucket.org/fathomteam/moab.git
    GIT_TAG ${MOAB_Version}
    CMAKE_ARGS
      -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
      -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
      -DENABLE_HDF5:BOOL=ON
      -DHDF5_ROOT:PATH=${HDF5_ROOT}
      -DCMAKE_INSTALL_RPATH=${HDF5_ROOT}/lib:${MOAB_INSTALL_PREFIX}/lib
      -DENABLE_BLASLAPACK:BOOL=OFF
      -DBUILD_SHARED_LIBS:BOOL=ON
      -DENABLE_FORTRAN:BOOL=OFF
      -DENABLE_PYMOAB:BOOL=OFF
      ${OPTION_FLAG}
    DOWNLOAD_EXTRACT_TIMESTAMP true
    BUILD_BYPRODUCTS "${MOAB_LIBRARY_DIRS}/*${CMAKE_SHARED_LIBRARY_SUFFIX}*"
    INSTALL_DIR "${MOAB_INSTALL_PREFIX}"
  )
  # SETup a interface library for MOAB based on ExternalProoject MOAB_EP
  ADD_LIBRARY(MOAB INTERFACE)

  TARGET_INCLUDE_DIRECTORIES(MOAB SYSTEM INTERFACE ${MOAB_INCLUDE_DIRS})
  TARGET_LINK_LIBRARIES(MOAB INTERFACE ${MOAB_LIBRARY_DIRS}/libMOAB${CMAKE_SHARED_LIBRARY_SUFFIX})
  ADD_DEPENDENCIES(MOAB MOAB_ep)
  INSTALL(TARGETS MOAB LIBRARY DESTINATION ${MOAB_LIBRARY_DIRS}
                      PUBLIC_HEADER DESTINATION ${INSTALL_INCLUDE_DIR})
  SET_SOURCE_FILES_PROPERTIES(
    ${MOAB_LIBRARY_DIRS}/libMOAB${CMAKE_SHARED_LIBRARY_SUFFIX} PROPERTIES
    EXTERNAL_OBJECT TRUE  # Identifies this as an object file
    GENERATED TRUE  # Avoids need for file to exist at configure-time
)
  INCLUDE_DIRECTORIES(${MOAB_INCLUDE_DIRS})
  LINK_DIRECTORIES(${MOAB_LIBRARY_DIRS})

  # Find HDF5
  INCLUDE(HDF5_macro)
  find_SET_HDF5()
  
  SET(CMAKE_FIND_LIBRARY_SUFFIXES ${CMAKE_SHARED_LIBRARY_SUFFIX})
  FIND_LIBRARY(MOAB_LIBRARIES_SHARED
    NAMES MOAB
    HINTS ${MOAB_LIBRARY_DIRS}
    NO_DEFAULT_PATH
  )
  LIST(APPEND MOAB_LIBRARIES_SHARED)
  MESSAGE(STATUS "MOAB_INCLUDE_DIRS: ${MOAB_INCLUDE_DIRS}")
  MESSAGE(STATUS "MOAB_LIBRARY_DIRS: ${MOAB_LIBRARY_DIRS}")
  MESSAGE(STATUS "MOAB_LIBRARIES_SHARED: ${MOAB_LIBRARIES_SHARED}")

ENDMACRO(moab_pull_make)


MACRO (moab_autobuild_check_deps)
# First check IF we are forcing the download of MOAB
IF (PULL_INSTALL_MOAB)
  IF (NOT DEFINED HDF5_ROOT)
    MESSAGE(FATAL_ERROR "HDF5_ROOT is required to build MOAB")
  ENDIF()

  IF (DEFINED ${EIGEN3_DIR})
    SET(OPTION_FLAG "-DEIGEN3_DIR=${EIGEN3_DIR}")
  ELSE()
    FIND_PACKAGE(Eigen3 REQUIRED NO_MODULE)
    INCLUDE_DIRECTORIES(${EIGEN3_INCLUDE_DIRS})
  ENDIF()

ENDIF ()

ENDMACRO (moab_autobuild_check_deps)