name: Mac Build/Test

on:
  # allows us to run workflows manually
  workflow_dispatch:
  pull_request:
    branches:
      - develop
    paths-ignore:
      - '.github/workflows/docker_publish.yml'
      - '.github/workflows/linux_build_test.yml'
      - '.github/workflows/linux_upstream_test_*'
      - '.github/workflows/windows_build_test.yml'
      - '.github/workflows/housekeeping.yml'
      - '.github/workflows/changelog_test.yml'
      - '.github/actions/**'
      - 'CI/**'
      - 'doc/**'

  push:
    branches:
      - develop
    paths-ignore:
      - '.github/workflows/docker_publish.yml'
      - '.github/workflows/linux_build_test.yml'
      - '.github/workflows/linux_upstream_test_*'
      - '.github/workflows/windows_build_test.yml'
      - '.github/workflows/housekeeping.yml'
      - '.github/workflows/changelog_test.yml'
      - '.github/actions/**'
      - 'CI/**'
      - 'doc/**'

  release:
    types: # This configuration does not affect the page_build event above
      - created
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  BuildTest:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Initial setup
        shell: bash -l {0}
        run: |
          brew install hdf5

      - name: Environment Variables
        shell: bash -l {0}
        run: |
          echo "HOME=$GITHUB_WORKSPACE/.." >> $GITHUB_ENV


      - name: Build MOAB
        shell: bash -l {0}
        run: |
          cd ${HOME}
          mkdir -pv moab/bld
          cd moab
          git clone https://bitbucket.org/fathomteam/moab -b 5.5.1 --depth 1 --shallow-submodules
          cd bld
          cmake ../moab -DENABLE_HDF5=ON \
                        -DENABLE_PYMOAB=OFF \
                        -DHDF5_ROOT=$HDF5_PATH \
                        -DBUILD_SHARED_LIBS=ON \
                        -DENABLE_BLASLAPACK=OFF \
                        -DENABLE_FORTRAN=OFF \
                        -DCMAKE_INSTALL_PREFIX=${HOME}/moab
          make
          make install
          rm -rf ${HOME}/moab/moab ${HOME}/moab/bld

      - name: Build DAGMC
        shell: bash -l {0}
        run: |
          mkdir -p $GITHUB_WORKSPACE/bld
          cd $GITHUB_WORKSPACE/bld
          cmake ../ -DMOAB_DIR=${HOME}/moab \
                    -DBUILD_CI_TESTS=ON \
                    -DBUILD_STATIC_EXE=OFF \
                    -DBUILD_SHARED_LIBS=ON \
                    -DBUILD_STATIC_LIBS=OFF \
                    -DCMAKE_CXX_FLAGS="-Werror=reorder" \
                    -DCMAKE_INSTALL_PREFIX=${HOME}/dagmc
          make
          make install

      - name: Testing DAGMC
        shell: bash -l {0}
        run: |
          cd $GITHUB_WORKSPACE/bld
          PATH=$GITHUB_WORKSPACE/bld/bin:$PATH make test
