name: Test the permissions for a simple build/push

on:
  # allows us to run workflows manually
  workflow_dispatch:
  pull_request:

jobs:
  build-dependency-img:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      
    strategy:
      matrix:
        ubuntu_versions : [
          22.04,
          ]
        compiler : [
          gcc,
          ]
        hdf5_versions : [
         1.10.4,
        ]
        moab_versions : [
         5.3.0,
        ]

    name: Installing Dependencies
    steps:        
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Installing Dependencies in Docker image & Testing DAGMC
        id: build
        uses: docker/build-push-action@v4
        with:
          context: CI/
          target: base
          push: true
          tags: ghcr.io/${{ github.actor }}/dagmc-ci-ubuntu-${{ matrix.ubuntu_versions }}-${{ matrix.compiler}}-ext-hdf5_${{ matrix.hdf5_versions}}-moab_${{ matrix.moab_versions }}/base:test
